### ISSUE TITLE
STX Issue in Supertrend while trying to run it.

### ISSUE THREAD

**Issue by RoshanaliN** [RajeshSivadasan/alice_blue#5]
Hi,
Can you please let me know why am I getting this issue, also if you have done some update to the code can you please share.
STX contains NaN as assigned in ab_lib.py from the supertrend function.

Traceback (most recent call last):
  File "C:/Users/Rex/Desktop/Trading/alice_blue-main_Rajesh/ab_options.py", line 1368, in <module>
    strMsg="BankNifty: #={}, ST_LOW={}, ST_LOW_SL={}, ATR={}, ST_MED={}, ST_MED_SL={}, ltp_bank_ATM_CE={}, ltp_bank_ATM_PE={}".format(df_bank_cnt, super_trend_bank[-1], round(df_bank.ST.iloc[-1]), round(df_bank.ATR.iloc[-1],1), df_bank_med.STX.iloc[-1], round(df_bank_med.ST.iloc[-1]), ltp_bank_ATM_CE, ltp_bank_ATM_PE)
  File "C:\Users\Rex\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'STX'

**Comment by RajeshSivadasan** [comment]
This issue has been fixed. Kindly pick the latest version

**Comment by sachuc** [comment]
Hardly anybidy has errors I get 50 errors in triple quotes Indention errors while running your code in jupyter notebook  Please help me I am doing something wrong

**Comment by RajeshSivadasan** [comment]
I am not using jupyter notebook instead I am using vscode on linux. Please make sure that the code indentation is not lost/mismatched while running the code in jupyter notebook.

**Comment by raviyellani** [comment]
Hi, may i know have you tested this algo in realtime market if so what is the accuracy range i.e TGT/SL hitting percentage

**Comment by RajeshSivadasan** [comment]
@raviyellani , Not tracking the accuracy till now. Wanted to get this working in all the scenarios. This algo was halted for some time due to an AWS issue. I am planning to start it again and post the trades/results. Basically a lot depends on the parameters you are setting to get this worked based on the learnings.
