### ISSUE TITLE
Key error while checking the order history in alice blue

### ISSUE THREAD

**Issue by arjuneshm** [RajeshSivadasan/alice_blue#6]
Hi,
Rajesh

I am frequently checking the order history of my orderId . Consider it is less than second time frame .

Following is the error i am getting, looks like the order history dictionary output is missing in between when i am querying.
================================================
Traceback (most recent call last):

orders = alice.get_order_history()["data"]["completed_orders"]
KeyError: 'completed_orders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
==================================================

Basically my script almost ran for 15 minutes in the loop where it was able to check the status continuously.
If you are able to judge, please guide me with some solution.

Sent the same issue to krishna also. Incase if you are aware please help me.

On further debug i understood that , after some 5 to 10minutes, there is a break happening for the output too. But that is not creating the exception.

If we run the following code for 1 hr  and notice we can see following 2 conditions : 
1.  Sometimes order history output will take a break of more than 30 seconds
2. Sometimes exception on the "order_complete" handle too.

Code used for checking : 

while(True):
                orders=alice.get_order_history()["data"]["completed_orders"]
                print(f'orders is {orders}')

Thanks and Regards
Arjunesh

**Comment by RajeshSivadasan** [comment]
Give a sleep duration (at least 1 to 10 seconds) between each call to get_order_history() and handle exception as completed_order keys might not get created immediately after order is placed.

**Comment by RajeshSivadasan** [comment]
Hope this issues is resolved. Kindly reopen with details if the issue persists.
